---
# taks file for common
- name: upgrade the system
  apt: update_cache=yes upgrade=safe cache_valid_time=3600

- name: determine language packages
  shell: check-language-support -l {{ locale.split('_')[0] }} 2>/dev/null
  register: language_packages
  changed_when: language_packages.stdout != ""
  ignore_errors: yes
  
- name: install language packages
  apt: name={{ item }} state=latest
  with_items: "{{ language_packages.stdout.split() }}"

- name: setup system locale
  command: update-locale --reset LANG={{ locale }}

- name: generate locale definitions
  locale_gen: name={{ locale }} state=present

- name: set keyboard configuration
  template: dest=/etc/default/keyboard src=keyboard.j2
  notify: update keyboard-configuration
  
- name: install vim editor
  apt: name=vim-tiny state=latest
  
- name: set vim as default editor
  alternatives: name=editor path=/usr/bin/vim.basic
