---
- hosts: all
  remote_user: root
  roles:
    - ubuntudesktop
    - byobu
    - vim
    - git
    - qtdevel
  tasks:
    - name: install project specific development tools
      apt: name={{ item }} state=latest
      with_items:
        - libcv-dev
        - sqlite3
        - sqliteman
        - netcat-openbsd
        - checkinstall
        - protobuf-compiler
        - libprotobuf-dev
